// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: internal/proto/gophkeeper.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CipheredData_Type int32

const (
	CipheredData_PASSWORD CipheredData_Type = 0
	CipheredData_DATA     CipheredData_Type = 1
	CipheredData_TEXT     CipheredData_Type = 2
	CipheredData_CC       CipheredData_Type = 3
)

// Enum value maps for CipheredData_Type.
var (
	CipheredData_Type_name = map[int32]string{
		0: "PASSWORD",
		1: "DATA",
		2: "TEXT",
		3: "CC",
	}
	CipheredData_Type_value = map[string]int32{
		"PASSWORD": 0,
		"DATA":     1,
		"TEXT":     2,
		"CC":       3,
	}
)

func (x CipheredData_Type) Enum() *CipheredData_Type {
	p := new(CipheredData_Type)
	*p = x
	return p
}

func (x CipheredData_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CipheredData_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_gophkeeper_proto_enumTypes[0].Descriptor()
}

func (CipheredData_Type) Type() protoreflect.EnumType {
	return &file_internal_proto_gophkeeper_proto_enumTypes[0]
}

func (x CipheredData_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CipheredData_Type.Descriptor instead.
func (CipheredData_Type) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_gophkeeper_proto_rawDescGZIP(), []int{0, 0}
}

type CipheredData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data      []byte            `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Type      CipheredData_Type `protobuf:"varint,2,opt,name=type,proto3,enum=gophkeeper.CipheredData_Type" json:"type,omitempty"`
	Useremail string            `protobuf:"bytes,3,opt,name=useremail,proto3" json:"useremail,omitempty"`
	Uuid      string            `protobuf:"bytes,4,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *CipheredData) Reset() {
	*x = CipheredData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_gophkeeper_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CipheredData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CipheredData) ProtoMessage() {}

func (x *CipheredData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CipheredData.ProtoReflect.Descriptor instead.
func (*CipheredData) Descriptor() ([]byte, []int) {
	return file_internal_proto_gophkeeper_proto_rawDescGZIP(), []int{0}
}

func (x *CipheredData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CipheredData) GetType() CipheredData_Type {
	if x != nil {
		return x.Type
	}
	return CipheredData_PASSWORD
}

func (x *CipheredData) GetUseremail() string {
	if x != nil {
		return x.Useremail
	}
	return ""
}

func (x *CipheredData) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type AddCipheredDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *CipheredData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *AddCipheredDataRequest) Reset() {
	*x = AddCipheredDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_gophkeeper_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddCipheredDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCipheredDataRequest) ProtoMessage() {}

func (x *AddCipheredDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCipheredDataRequest.ProtoReflect.Descriptor instead.
func (*AddCipheredDataRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_gophkeeper_proto_rawDescGZIP(), []int{1}
}

func (x *AddCipheredDataRequest) GetData() *CipheredData {
	if x != nil {
		return x.Data
	}
	return nil
}

type AddCipheredDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddCipheredDataResponse) Reset() {
	*x = AddCipheredDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_gophkeeper_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddCipheredDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCipheredDataResponse) ProtoMessage() {}

func (x *AddCipheredDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCipheredDataResponse.ProtoReflect.Descriptor instead.
func (*AddCipheredDataResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_gophkeeper_proto_rawDescGZIP(), []int{2}
}

type GetCipheredDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *GetCipheredDataRequest) Reset() {
	*x = GetCipheredDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_gophkeeper_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCipheredDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCipheredDataRequest) ProtoMessage() {}

func (x *GetCipheredDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCipheredDataRequest.ProtoReflect.Descriptor instead.
func (*GetCipheredDataRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_gophkeeper_proto_rawDescGZIP(), []int{3}
}

func (x *GetCipheredDataRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetCipheredDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*CipheredData `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetCipheredDataResponse) Reset() {
	*x = GetCipheredDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_gophkeeper_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCipheredDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCipheredDataResponse) ProtoMessage() {}

func (x *GetCipheredDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCipheredDataResponse.ProtoReflect.Descriptor instead.
func (*GetCipheredDataResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_gophkeeper_proto_rawDescGZIP(), []int{4}
}

func (x *GetCipheredDataResponse) GetData() []*CipheredData {
	if x != nil {
		return x.Data
	}
	return nil
}

type DelCipheredDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *DelCipheredDataRequest) Reset() {
	*x = DelCipheredDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_gophkeeper_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelCipheredDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelCipheredDataRequest) ProtoMessage() {}

func (x *DelCipheredDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelCipheredDataRequest.ProtoReflect.Descriptor instead.
func (*DelCipheredDataRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_gophkeeper_proto_rawDescGZIP(), []int{5}
}

func (x *DelCipheredDataRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type DelCiphereDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DelCiphereDataResponse) Reset() {
	*x = DelCiphereDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_gophkeeper_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelCiphereDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelCiphereDataResponse) ProtoMessage() {}

func (x *DelCiphereDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelCiphereDataResponse.ProtoReflect.Descriptor instead.
func (*DelCiphereDataResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_gophkeeper_proto_rawDescGZIP(), []int{6}
}

var File_internal_proto_gophkeeper_proto protoreflect.FileDescriptor

var file_internal_proto_gophkeeper_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0a, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x22, 0xb9, 0x01,
	0x0a, 0x0c, 0x43, 0x69, 0x70, 0x68, 0x65, 0x72, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x31, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x1d, 0x2e, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x43, 0x69,
	0x70, 0x68, 0x65, 0x72, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x30, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x0c, 0x0a, 0x08, 0x50, 0x41, 0x53, 0x53, 0x57, 0x4f, 0x52, 0x44, 0x10, 0x00, 0x12, 0x08, 0x0a,
	0x04, 0x44, 0x41, 0x54, 0x41, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x45, 0x58, 0x54, 0x10,
	0x02, 0x12, 0x06, 0x0a, 0x02, 0x43, 0x43, 0x10, 0x03, 0x22, 0x46, 0x0a, 0x16, 0x41, 0x64, 0x64,
	0x43, 0x69, 0x70, 0x68, 0x65, 0x72, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x43,
	0x69, 0x70, 0x68, 0x65, 0x72, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x19, 0x0a, 0x17, 0x41, 0x64, 0x64, 0x43, 0x69, 0x70, 0x68, 0x65, 0x72, 0x65, 0x64,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2e, 0x0a, 0x16,
	0x47, 0x65, 0x74, 0x43, 0x69, 0x70, 0x68, 0x65, 0x72, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x47, 0x0a, 0x17,
	0x47, 0x65, 0x74, 0x43, 0x69, 0x70, 0x68, 0x65, 0x72, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70,
	0x65, 0x72, 0x2e, 0x43, 0x69, 0x70, 0x68, 0x65, 0x72, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x2c, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x43, 0x69, 0x70, 0x68,
	0x65, 0x72, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75,
	0x75, 0x69, 0x64, 0x22, 0x18, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x43, 0x69, 0x70, 0x68, 0x65, 0x72,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xad, 0x02,
	0x0a, 0x0a, 0x47, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x12, 0x5a, 0x0a, 0x0f,
	0x41, 0x64, 0x64, 0x43, 0x69, 0x70, 0x68, 0x65, 0x72, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x22, 0x2e, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x41, 0x64, 0x64,
	0x43, 0x69, 0x70, 0x68, 0x65, 0x72, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72,
	0x2e, 0x41, 0x64, 0x64, 0x43, 0x69, 0x70, 0x68, 0x65, 0x72, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x68, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x43,
	0x69, 0x70, 0x68, 0x65, 0x72, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x46, 0x6f, 0x72, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x2e, 0x67, 0x6f, 0x70, 0x68,
	0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x69, 0x70, 0x68, 0x65, 0x72,
	0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e,
	0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x69,
	0x70, 0x68, 0x65, 0x72, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x59, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x43, 0x69, 0x70, 0x68, 0x65, 0x72, 0x65,
	0x64, 0x44, 0x61, 0x74, 0x61, 0x12, 0x22, 0x2e, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70,
	0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x43, 0x69, 0x70, 0x68, 0x65, 0x72, 0x65, 0x64, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x67, 0x6f, 0x70, 0x68,
	0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x43, 0x69, 0x70, 0x68, 0x65, 0x72,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1b, 0x5a,
	0x19, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_internal_proto_gophkeeper_proto_rawDescOnce sync.Once
	file_internal_proto_gophkeeper_proto_rawDescData = file_internal_proto_gophkeeper_proto_rawDesc
)

func file_internal_proto_gophkeeper_proto_rawDescGZIP() []byte {
	file_internal_proto_gophkeeper_proto_rawDescOnce.Do(func() {
		file_internal_proto_gophkeeper_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_proto_gophkeeper_proto_rawDescData)
	})
	return file_internal_proto_gophkeeper_proto_rawDescData
}

var file_internal_proto_gophkeeper_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_proto_gophkeeper_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_internal_proto_gophkeeper_proto_goTypes = []interface{}{
	(CipheredData_Type)(0),          // 0: gophkeeper.CipheredData.Type
	(*CipheredData)(nil),            // 1: gophkeeper.CipheredData
	(*AddCipheredDataRequest)(nil),  // 2: gophkeeper.AddCipheredDataRequest
	(*AddCipheredDataResponse)(nil), // 3: gophkeeper.AddCipheredDataResponse
	(*GetCipheredDataRequest)(nil),  // 4: gophkeeper.GetCipheredDataRequest
	(*GetCipheredDataResponse)(nil), // 5: gophkeeper.GetCipheredDataResponse
	(*DelCipheredDataRequest)(nil),  // 6: gophkeeper.DelCipheredDataRequest
	(*DelCiphereDataResponse)(nil),  // 7: gophkeeper.DelCiphereDataResponse
}
var file_internal_proto_gophkeeper_proto_depIdxs = []int32{
	0, // 0: gophkeeper.CipheredData.type:type_name -> gophkeeper.CipheredData.Type
	1, // 1: gophkeeper.AddCipheredDataRequest.data:type_name -> gophkeeper.CipheredData
	1, // 2: gophkeeper.GetCipheredDataResponse.data:type_name -> gophkeeper.CipheredData
	2, // 3: gophkeeper.Gophkeeper.AddCipheredData:input_type -> gophkeeper.AddCipheredDataRequest
	4, // 4: gophkeeper.Gophkeeper.GetCipheredDataForUserRequest:input_type -> gophkeeper.GetCipheredDataRequest
	6, // 5: gophkeeper.Gophkeeper.DelCipheredData:input_type -> gophkeeper.DelCipheredDataRequest
	3, // 6: gophkeeper.Gophkeeper.AddCipheredData:output_type -> gophkeeper.AddCipheredDataResponse
	5, // 7: gophkeeper.Gophkeeper.GetCipheredDataForUserRequest:output_type -> gophkeeper.GetCipheredDataResponse
	7, // 8: gophkeeper.Gophkeeper.DelCipheredData:output_type -> gophkeeper.DelCiphereDataResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_proto_gophkeeper_proto_init() }
func file_internal_proto_gophkeeper_proto_init() {
	if File_internal_proto_gophkeeper_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_proto_gophkeeper_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CipheredData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_gophkeeper_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddCipheredDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_gophkeeper_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddCipheredDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_gophkeeper_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCipheredDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_gophkeeper_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCipheredDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_gophkeeper_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelCipheredDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_gophkeeper_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelCiphereDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_proto_gophkeeper_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_gophkeeper_proto_goTypes,
		DependencyIndexes: file_internal_proto_gophkeeper_proto_depIdxs,
		EnumInfos:         file_internal_proto_gophkeeper_proto_enumTypes,
		MessageInfos:      file_internal_proto_gophkeeper_proto_msgTypes,
	}.Build()
	File_internal_proto_gophkeeper_proto = out.File
	file_internal_proto_gophkeeper_proto_rawDesc = nil
	file_internal_proto_gophkeeper_proto_goTypes = nil
	file_internal_proto_gophkeeper_proto_depIdxs = nil
}
